name: Daily update NL info

on:
  push:
    branches: [dev-0.0.2]
  # schedule:
  #   - cron: "11/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Get all files
        run: |
          pwd
          ls
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Python Requirements
        run: |
          python --version
          pip install -r requirements.txt
      - name: Run workflow
        run: |
          python src/workflow.py
          ls dataset/daily/nl
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git status
          git add .
          git commit -m "Update NL Dataset" || echo "Nothing to update"
          git status
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: ZequnZ/COVID-19-NL
          github_token: ${{ secrets.GITHUB_TOKEN }}
